import { Inter } from "next/font/google";
import NavBar from "./navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-800">
        <NavBar />
        <main className="container mx-auto px-5 mt-4 bg-gray-700">
          {children}
        </main>
      </body>
    </html>
  );
}
